// Blog content. Each post: slug, title, excerpt, category, author, date,
// readMins, keywords[], and body[] of blocks ({p|h2|ul|quote|fig}).
// A fig block ({ fig: "scene-name", caption }) renders an inline illustration
// from components/BlogArt.jsx (see its NAMED registry for valid scene names).
// SEO metadata + JSON-LD are generated from these fields on the post page.

export const blogCategories = [
  "Paid Media",
  "ASO",
  "SEO",
  "Creative",
  "Retention",
  "Analytics",
  "Strategy",
];

// Gradient accent per category — used on cards and post headers.
export const categoryAccent = {
  "Paid Media": { from: "#6366F1", to: "#8B5CF6" },
  ASO: { from: "#8B5CF6", to: "#D946EF" },
  SEO: { from: "#34D399", to: "#10B981" },
  Creative: { from: "#F472B6", to: "#D946EF" },
  Retention: { from: "#22D3EE", to: "#0EA5E9" },
  Analytics: { from: "#FBBF24", to: "#F59E0B" },
  Strategy: { from: "#60A5FA", to: "#6366F1" },
};

// Contextual CTA per category, used on each post page.
export const ctaByCategory = {
  "Paid Media": { title: "Want paid acquisition that actually pays back?", body: "Book a free teardown — we’ll audit your accounts and show you where the efficient growth is hiding.", label: "Book a free teardown", href: "/contact" },
  ASO: { title: "Ready to climb the store rankings?", body: "Get a free ASO audit of your listing, keywords, and conversion rate.", label: "Get an ASO audit", href: "/contact" },
  SEO: { title: "Own the search surfaces your buyers use", body: "Let’s map an organic strategy that compounds month over month.", label: "Talk to our SEO team", href: "/contact" },
  Creative: { title: "Never run out of winning creative", body: "See how our in-house studio ships performance creative every week.", label: "See how we work", href: "/services" },
  Retention: { title: "Plug the leaks in your funnel", body: "Acquisition without retention is a leaky bucket. Let’s fix the whole system.", label: "Book a teardown", href: "/contact" },
  Analytics: { title: "Trust your numbers again", body: "We’ll rebuild your attribution so every dollar is traceable to revenue.", label: "Get an attribution audit", href: "/contact" },
  Strategy: { title: "Build an acquisition engine that compounds", body: "Book a free 30-minute teardown and walk away with a 90-day plan.", label: "Book a free teardown", href: "/contact" },
};

const A = {
  elena: "Elena Marković",
  tomas: "Tomas Reyes",
  aisha: "Aisha Bello",
  kenji: "Kenji Watanabe",
};

// Author bios, shown at the end of each post. Keyed by author name.
export const authors = {
  "Elena Marković": {
    role: "Founder & Growth Lead",
    initials: "EM",
    bio: "Elena founded Lumivance after a decade running growth in-house at SaaS and fintech companies. She writes about acquisition strategy, unit economics, and building engines that compound.",
  },
  "Tomas Reyes": {
    role: "Head of Paid Media",
    initials: "TR",
    bio: "Tomas has managed eight figures of paid spend across Meta, Google, TikTok, and Apple Search Ads. He writes about performance media, scaling, and channel diversification.",
  },
  "Aisha Bello": {
    role: "Creative Director",
    initials: "AB",
    bio: "Aisha leads Lumivance’s in-house creative studio. She writes about performance creative, UGC, and turning ad concepts into repeatable winners.",
  },
  "Kenji Watanabe": {
    role: "Head of Analytics",
    initials: "KW",
    bio: "Kenji builds the attribution and measurement systems behind Lumivance’s work. He writes about analytics, incrementality, and making numbers you can trust.",
  },
};

export function getAuthor(name) {
  return authors[name] || { role: "Growth Team", initials: "LV", bio: "" };
}

export const posts = [
  {
    slug: "lower-cost-per-install-without-killing-volume",
    title: "How to Lower Your Cost Per Install Without Killing Volume",
    excerpt: "Cutting CPI usually means cutting reach — unless you attack the right levers. Here’s the order of operations we use to drop install costs while scaling.",
    category: "Paid Media",
    author: A.tomas,
    date: "2025-03-04",
    readMins: 11,
    keywords: ["cost per install", "CPI optimization", "app install ads", "user acquisition", "mobile marketing"],
    body: [
      { p: "Most teams try to lower cost per install (CPI) by trimming bids. That works for a week, then volume collapses. Sustainable CPI reduction comes from the creative, the funnel, and the targeting — in that order." },
      { h2: "Start with creative, not bids" },
      { p: "Creative is responsible for the majority of performance variance in modern auctions. Before you touch a bid, ship three to five new concepts that attack different hooks, angles, and formats. A single winning ad can do more for your CPI than weeks of bid tuning." },
      { fig: "ad-grid", caption: "Concept-level testing: one winning ad can move CPI more than a month of bid changes." },
      { h2: "Fix the click-to-install gap" },
      { p: "If your store listing or landing page converts poorly, you’re paying for clicks that never become installs. Audit your app store creative set, your first screenshot, and your load time before blaming the ad platform." },
      { fig: "store-phone", caption: "Your store listing is part of the ad — audit it before blaming the auction." },
      { h2: "Let the algorithm find efficiency" },
      { p: "Broad targeting with strong creative signals usually beats narrow audiences. Give the platform room to optimize, feed it clean conversion events, and resist the urge to over-segment." },
      { h2: "Sequence changes so you can read them" },
      { p: "CPI work goes wrong when five things change at once. Adjust creative one week, targeting the next, and bids only after the first two stabilize. A change log — date, change, expected effect — turns your account history into a lab notebook, and it’s the first thing we rebuild when we inherit an account in chaos." },
      { h2: "Guardrails: watch quality while you cut cost" },
      { p: "A falling CPI is only a win if the users you buy still activate and retain. Pair every CPI target with a quality guardrail — day-1 activation or day-7 retention — and treat a cheap install that never opens the app as what it is: waste with better optics." },
      { quote: "The cheapest install is rarely the best install — the best install is the one that pays you back." },
      { h2: "Key takeaways" },
      { ul: ["Creative drives most of your CPI — test it weekly", "Optimize the store listing, not just the ad", "Use broad targeting with clean events", "Change one variable at a time so you can read the result", "Guard every CPI cut with a retention check"] },
    ],
  },
  {
    slug: "cac-payback-period-metric-that-matters",
    title: "CAC Payback Period: The Only Acquisition Metric That Matters",
    excerpt: "ROAS and CPI are useful, but payback period is the metric that tells you whether you can scale. Here’s how to calculate and use it.",
    category: "Strategy",
    author: A.elena,
    date: "2025-02-18",
    readMins: 10,
    keywords: ["CAC payback period", "customer acquisition cost", "unit economics", "SaaS metrics", "growth strategy"],
    body: [
      { p: "CAC payback period is the number of months it takes to earn back what you spent acquiring a customer. It’s the single best signal of whether your acquisition is sustainable — and whether you can afford to spend more." },
      { h2: "The formula" },
      { p: "Payback period = CAC ÷ (monthly gross margin per customer). If you spend $300 to acquire a customer who delivers $50 in monthly gross margin, your payback is six months." },
      { fig: "gauge", caption: "Payback sets the ceiling on how hard you can push spend without outrunning your cash." },
      { h2: "Why it beats ROAS" },
      { p: "ROAS flatters channels that capture demand you already had. Payback period forces you to reckon with margin and time — the two things that actually determine whether growth funds itself or bleeds cash." },
      { h2: "What good looks like" },
      { p: "For most software businesses, a payback under 12 months is healthy and under 6 is excellent. The shorter your payback, the faster you can recycle capital into more acquisition." },
      { h2: "Segment it or it will lie to you" },
      { p: "A blended six-month payback can hide a two-month channel subsidizing a fourteen-month one. Cut the number by channel, campaign, and cohort month. The segments tell you where to press and where to pull back — the blended average just tells you a comfortable story." },
      { fig: "cohort-curves", caption: "Payback by monthly cohort: improving cohorts are the clearest sign your engine is getting healthier." },
      { h2: "Payback is a financing decision" },
      { p: "How much payback you can tolerate is really a question about your balance sheet. Venture-funded teams can often finance twelve months; bootstrapped teams usually need six or less. Set the tolerance with your finance lead, then let marketing optimize freely inside it." },
      { quote: "Growth you can’t finance isn’t growth — it’s a countdown." },
      { h2: "Key takeaways" },
      { ul: ["Payback ties spend to margin and time", "Under 12 months is healthy for most SaaS", "Use it to decide how aggressively to scale", "Track it by channel and cohort, not just blended"] },
    ],
  },
  {
    slug: "founders-guide-to-aso",
    title: "A Founder’s Guide to App Store Optimization (ASO)",
    excerpt: "ASO is the cheapest, most durable install channel you have. This is the founder-level overview of how it works and where to start.",
    category: "ASO",
    author: A.aisha,
    date: "2025-04-09",
    readMins: 12,
    keywords: ["ASO", "app store optimization", "keyword optimization", "app store ranking", "organic installs"],
    body: [
      { p: "App Store Optimization is the practice of improving your app’s visibility and conversion in the App Store and Google Play. Done well, it compounds: better rankings drive more installs, which drive better rankings." },
      { h2: "The two halves of ASO" },
      { p: "ASO splits into discovery (ranking for the keywords people search) and conversion (turning a store visit into an install). Most teams obsess over the first and ignore the second — but conversion gains lift every channel, including paid." },
      { fig: "search-result", caption: "Discovery: winning the queries your buyers actually type into the store." },
      { h2: "Keywords that matter" },
      { p: "Target keywords with real search volume and realistic difficulty. Use your title and subtitle for your highest-value terms, and fill the keyword field (iOS) without repeating words." },
      { h2: "Convert the visit" },
      { p: "Your icon, first two screenshots, and rating drive the install decision in seconds. Test screenshot concepts the same way you test ad creative — the lift is often larger." },
      { h2: "Reviews are a ranking factor — and a sales team" },
      { p: "Both stores read rating velocity and review sentiment. Prompt for a rating right after a moment of delivered value — a finished workout, a completed export — never at first launch. Reply to negative reviews; a thoughtful response is visible to every future visitor, not just the reviewer." },
      { h2: "Make it compound" },
      { p: "ASO isn’t a one-time optimization. Rankings feed installs, installs feed velocity, velocity feeds rankings. Review your keyword coverage monthly, refresh screenshots quarterly, and treat every store algorithm update as a chance to take ground competitors are slow to defend." },
      { fig: "flywheel", caption: "The ASO flywheel: rankings, installs, and velocity feeding each other." },
      { h2: "Key takeaways" },
      { ul: ["ASO compounds — start early", "Optimize discovery and conversion, not just keywords", "Your first screenshots do the heavy lifting", "Run store listing experiments continuously"] },
    ],
  },
  {
    slug: "meta-ads-for-saas-full-funnel-playbook",
    title: "Meta Ads for SaaS: A Full-Funnel Playbook",
    excerpt: "Meta isn’t just for ecommerce. Here’s how to run profitable full-funnel campaigns for a B2B or prosumer SaaS product.",
    category: "Paid Media",
    author: A.tomas,
    date: "2025-05-21",
    readMins: 13,
    keywords: ["Meta ads", "Facebook ads for SaaS", "B2B paid social", "full funnel marketing", "lead generation"],
    body: [
      { p: "Meta works for software — if you stop copying ecommerce playbooks. SaaS has longer consideration cycles and higher-value conversions, so your funnel, creative, and measurement need to match." },
      { h2: "Structure the funnel" },
      { p: "Run broad prospecting to a strong value proposition, then retarget engaged users with proof and product depth. Don’t expect a cold click to start a trial — earn the consideration first." },
      { h2: "Optimize to the right event" },
      { p: "Optimizing to clicks gets you clicks. Optimize to qualified signups or trials, and pass those events back via the Conversions API so the algorithm learns from quality, not quantity." },
      { fig: "server-relay", caption: "The Conversions API feeds qualified events back so Meta optimizes for quality, not clicks." },
      { h2: "Creative that sells software" },
      { p: "Show the product. Demos, before/after workflows, and customer outcomes outperform polished brand films for performance. Talk benefits, not features." },
      { fig: "ad-grid", caption: "Testing product-led concepts: demos and workflows beat brand films for performance." },
      { h2: "Budget split that respects the journey" },
      { p: "A working default is 70% prospecting, 30% retargeting — then adjust by watching marginal cost per qualified signup on each side. Starving prospecting to feast retargeting flatters your dashboards this month and empties your pipeline next quarter." },
      { h2: "Judge it on pipeline, not platform ROAS" },
      { p: "For SaaS, the sale often closes weeks after the click, off-platform. Pull campaign data into your CRM, tag opportunities to their source, and evaluate Meta on the pipeline and revenue it originates — not the conversions it claims." },
      { h2: "Key takeaways" },
      { ul: ["Separate prospecting and retargeting", "Optimize to qualified events via CAPI", "Show the product doing real work", "Measure pipeline, not just leads"] },
    ],
  },
  {
    slug: "why-your-roas-is-lying-to-you",
    title: "Why Your ROAS Is Lying to You (and What to Track Instead)",
    excerpt: "Platform-reported ROAS double-counts, over-attributes, and ignores margin. Here’s how to see the truth.",
    category: "Analytics",
    author: A.kenji,
    date: "2025-03-27",
    readMins: 11,
    keywords: ["ROAS", "return on ad spend", "attribution", "incrementality", "marketing measurement"],
    body: [
      { p: "Every ad platform claims credit for the same conversion. Add up the ROAS each one reports and you’ll often ‘earn’ more revenue than your business actually made. That’s the attribution illusion." },
      { h2: "The three problems" },
      { p: "Platform ROAS over-attributes (claims sales it didn’t cause), ignores gross margin, and double-counts across channels. Optimizing to it pushes budget toward whoever reports most aggressively." },
      { fig: "ab-split", caption: "Holdout tests reveal what a channel actually caused — attribution only reveals what it claimed." },
      { h2: "Track blended and incremental" },
      { p: "Blended ROAS (total revenue ÷ total spend) keeps you honest at the top line. Incrementality tests tell you what each channel actually caused. Use platform numbers only for in-channel optimization." },
      { h2: "A sanity check you can run today" },
      { p: "Add up last month’s platform-reported revenue across every channel and compare it to what finance booked. The gap between those two numbers is the size of your attribution illusion — and for most teams it’s 30–60%." },
      { fig: "dashboard", caption: "A blended view — total revenue over total spend — keeps every channel honest." },
      { h2: "Build the measurement stack in layers" },
      { p: "Use platform metrics for day-to-day creative and bid decisions, blended metrics for budget decisions, and incrementality tests for channel-level truth a few times a year. Each layer answers a different question; the mistake is asking one layer to answer all three." },
      { h2: "Key takeaways" },
      { ul: ["Platform ROAS over-attributes and ignores margin", "Use blended ROAS for the truth", "Run incrementality tests for causal answers", "Never set budgets on platform ROAS alone"] },
    ],
  },
  {
    slug: "performance-creative-ship-winning-ads-weekly",
    title: "Performance Creative: How to Ship Winning Ads Every Week",
    excerpt: "Creative is the biggest lever in paid acquisition. Here’s the operating system we use to produce winners on a weekly cadence.",
    category: "Creative",
    author: A.aisha,
    date: "2025-06-11",
    readMins: 12,
    keywords: ["performance creative", "ad creative testing", "UGC ads", "creative strategy", "paid social creative"],
    body: [
      { p: "In modern auctions, creative is the targeting. The teams that win are the ones who can reliably produce and test new concepts every single week — not the ones with the cleverest bid strategy." },
      { h2: "Separate concepts from variations" },
      { p: "A concept is a new hook or angle; a variation is a tweak to a proven concept. Spend your testing budget discovering concepts, then squeeze winners with variations." },
      { fig: "test-flask", caption: "Concepts are experiments: fund them properly, read them honestly, and keep the learnings." },
      { h2: "Build a hook library" },
      { p: "Catalog the hooks, formats, and angles that work in your category. Fresh creative is mostly recombination — a strong hook library makes weekly output sustainable." },
      { h2: "Read results honestly" },
      { p: "Give each concept enough spend to reach significance, kill losers fast, and document why winners won. The learning compounds faster than any single ad." },
      { h2: "The weekly rhythm that makes it sustainable" },
      { p: "Monday: read last week’s tests and pick winners. Tuesday: brief the next batch. Wednesday and Thursday: produce. Friday: launch. It sounds mechanical because it is — creativity thrives inside the cadence, not instead of it." },
      { fig: "ugc-phone", caption: "Formats are levers too: the same concept can live as UGC, static, or demo footage." },
      { h2: "Staff it like a product team" },
      { p: "One strategist, one editor, and one designer can sustain eight to twelve new ads a week if concepts are briefed sharply. The bottleneck is almost never production capacity — it’s concept clarity." },
      { quote: "Creative is the targeting now — the algorithm just delivers what your ads deserve." },
      { h2: "Key takeaways" },
      { ul: ["Treat creative as the primary lever", "Test concepts, scale with variations", "Keep a living hook library", "Document why winners win"] },
    ],
  },
  {
    slug: "beginners-guide-to-apple-search-ads",
    title: "The Beginner’s Guide to Apple Search Ads",
    excerpt: "Apple Search Ads captures high-intent users at the moment of decision. Here’s how to launch without wasting budget.",
    category: "Paid Media",
    author: A.tomas,
    date: "2025-02-25",
    readMins: 10,
    keywords: ["Apple Search Ads", "ASA", "app store ads", "mobile user acquisition", "iOS marketing"],
    body: [
      { p: "Apple Search Ads (ASA) puts your app at the top of relevant App Store searches. Because intent is so high, it’s often the most efficient paid channel for iOS apps — if you structure it right." },
      { h2: "Start with brand and competitor terms" },
      { p: "Bid on your own brand to defend it cheaply, then test competitor and category terms. Brand traffic is the highest-converting and protects against rivals poaching your searches." },
      { fig: "store-phone", caption: "ASA traffic lands on your listing — conversion rate there is half the battle." },
      { h2: "Use exact match to learn" },
      { p: "Begin with exact match on a focused keyword list, then mine search term reports from broad/discovery campaigns to expand. Negative keywords keep spend clean." },
      { h2: "A structure that scales" },
      { p: "Run four campaign types — brand, competitor, category, and discovery — with exact-match keywords in the first three and search match only in discovery. Graduate proven terms out of discovery into exact campaigns weekly, and keep negatives synced so campaigns never bid against each other." },
      { h2: "Price keywords by intent, not install rate" },
      { p: "Brand terms convert several times better than category terms — pricing them the same wastes budget. Set bids from each keyword’s downstream conversion rate, not its tap-through rate, and let high-intent terms carry the aggressive bids." },
      { fig: "chart-down", caption: "Mined search terms plus tight negatives push cost per install down over time." },
      { h2: "Key takeaways" },
      { ul: ["ASA captures high-intent searchers", "Defend brand terms first", "Learn with exact match, expand with discovery", "Use negatives to control spend"] },
    ],
  },
  {
    slug: "plg-vs-paid-acquisition",
    title: "Product-Led Growth vs. Paid Acquisition: Which Should You Start With?",
    excerpt: "PLG and paid aren’t rivals — they’re phases. Here’s how to decide where to put your first growth dollars.",
    category: "Strategy",
    author: A.elena,
    date: "2025-04-22",
    readMins: 11,
    keywords: ["product-led growth", "PLG", "paid acquisition", "go-to-market", "startup growth"],
    body: [
      { p: "Founders often frame product-led growth and paid acquisition as a choice. In practice, the order depends on your activation rate and your willingness to pay for distribution." },
      { h2: "Earn the right to spend" },
      { p: "If new users don’t activate and stick, paid spend just accelerates churn. Nail onboarding and retention first — then paid pours fuel on a fire that’s already lit." },
      { fig: "steps-spark", caption: "Activation is the gate: users who reach first value quickly are the ones worth paying for." },
      { h2: "When paid makes sense early" },
      { p: "If you have strong activation and a clear payback model, paid can validate channels and accelerate learning before PLG loops mature. The two compound when sequenced well." },
      { h2: "Run the audit before the debate" },
      { p: "Before arguing channels, measure three numbers: signup-to-activation rate, week-4 retention, and time-to-value. If activation is under 25% or retention decays to zero, fix the product loop first — no channel strategy survives a product users don’t return to." },
      { h2: "A simple sequencing playbook" },
      { p: "Quarter one: instrument and fix activation. Quarter two: small paid tests to validate two channels and gather learning. Quarter three: scale the winner while PLG loops — referrals, templates, shared artifacts — mature underneath. Paid and product-led growth compound when sequenced, and stall when forced to compete." },
      { fig: "loop-funnel", caption: "PLG loops feed the funnel’s top while paid accelerates what already works." },
      { h2: "Key takeaways" },
      { ul: ["Activation gates everything", "Fix retention before scaling paid", "Paid validates channels fast", "Sequence PLG and paid — don’t pick one forever"] },
    ],
  },
  {
    slug: "build-a-user-acquisition-funnel-that-compounds",
    title: "How to Build a User-Acquisition Funnel That Compounds",
    excerpt: "A funnel that only works while you’re spending isn’t an engine. Here’s how to build acquisition that gets cheaper over time.",
    category: "Strategy",
    author: A.elena,
    date: "2025-05-06",
    readMins: 12,
    keywords: ["acquisition funnel", "growth loops", "compounding growth", "user acquisition strategy", "marketing funnel"],
    body: [
      { p: "Most funnels are linear: spend in, users out. Compounding funnels reinvest outputs — content, referrals, reviews, data — back into the top, so each cycle is cheaper than the last." },
      { h2: "Layer durable channels under paid" },
      { p: "Paid buys speed, but SEO, ASO, and referral build equity. Run paid to learn and to fund the durable channels that lower your blended cost over time." },
      { fig: "page-grid", caption: "Content and SEO assets keep acquiring long after the campaign that funded them ends." },
      { h2: "Turn users into a channel" },
      { p: "Reviews, referrals, and user-generated content are acquisition inputs. Design moments that ask happy users to bring the next one." },
      { h2: "Measure the engine, not the month" },
      { p: "The health metric of a compounding funnel is blended CAC trending down while volume trends up. Any agency can buy a good month; an engine shows up as a two-year chart where each quarter acquires more users for less." },
      { fig: "flywheel", caption: "Each cycle reinvests outputs — reviews, referrals, content, data — back into the top." },
      { h2: "Budget like a portfolio" },
      { p: "Split spend three ways: proven channels that pay this quarter, durable assets that pay next year, and experiments that might become either. Teams that put everything in the first bucket stay on the treadmill forever." },
      { h2: "Key takeaways" },
      { ul: ["Linear funnels stop when spend stops", "Fund durable channels with paid learnings", "Make users an acquisition input", "Measure blended cost trending down"] },
    ],
  },
  {
    slug: "retention-is-the-new-acquisition",
    title: "Retention Is the New Acquisition: A Lifecycle Marketing Primer",
    excerpt: "You can’t outspend a leaky bucket. Here’s how lifecycle marketing turns installs into lasting revenue.",
    category: "Retention",
    author: A.aisha,
    date: "2025-03-14",
    readMins: 11,
    keywords: ["retention", "lifecycle marketing", "churn reduction", "onboarding", "engagement"],
    body: [
      { p: "Acquisition gets the headlines, but retention pays the bills. A small lift in retention compounds across every cohort and quietly lowers your effective CAC." },
      { h2: "Map the lifecycle" },
      { p: "Identify the moments that matter: first value, habit formation, and resurrection. Each deserves its own messaging across push, email, and in-app." },
      { fig: "cohort-curves", caption: "Cohorts make retention visible: the curve that flattens is the one funding your growth." },
      { h2: "Earn the first win fast" },
      { p: "The faster a new user reaches their ‘aha’ moment, the more likely they stay. Strip onboarding to the shortest path to value." },
      { h2: "Coordinate the channels" },
      { p: "Push, email, and in-app messages are one conversation, not three campaigns. Sequence them around behavior: in-app nudges while the user is present, push to bring them back, email for depth. Frequency caps across channels keep helpful from becoming noise." },
      { fig: "push-bell", caption: "Behavior-triggered messages outperform broadcast blasts — and get uninstalled less." },
      { h2: "Resurrection is cheaper than acquisition" },
      { p: "A lapsed user already knows your product — win-back campaigns routinely cost a fraction of cold acquisition. Segment the recently-lapsed from the long-gone, lead with what’s new or what they left behind, and measure reactivation as its own funnel." },
      { h2: "Key takeaways" },
      { ul: ["Retention lowers effective CAC", "Map first value, habit, resurrection", "Shorten time-to-value", "Coordinate push, email, and in-app"] },
    ],
  },
  {
    slug: "ugc-ads-that-convert",
    title: "UGC Ads That Convert: A Framework for Software Brands",
    excerpt: "User-generated content outperforms polished ads — but only with the right structure. Here’s the framework we brief creators with.",
    category: "Creative",
    author: A.aisha,
    date: "2025-06-24",
    readMins: 11,
    keywords: ["UGC ads", "user generated content", "creator marketing", "performance creative", "video ads"],
    body: [
      { p: "UGC works because it feels native and trustworthy. But ‘film a creator using the app’ isn’t a strategy. The structure of the script is what drives conversion." },
      { h2: "Lead with a problem hook" },
      { p: "The first three seconds decide everything. Open on a relatable problem or a pattern interrupt, not your logo." },
      { fig: "video-phone", caption: "Native-feeling video: the ad that doesn’t announce itself gets watched." },
      { h2: "Show the product solving it" },
      { p: "Move quickly to the product doing real work. Authentic screen capture beats glossy mockups for performance." },
      { h2: "Brief the structure, cast for credibility" },
      { p: "Give creators a beat sheet — hook, problem, product moment, outcome, call to action — and freedom over the words. Cast for believability in your niche, not follower count; an authentic mid-size creator outperforms a polished influencer for direct response." },
      { fig: "test-flask", caption: "Treat each creator video as a concept test: the script structure is the variable." },
      { h2: "Rights, whitelisting, and scale" },
      { p: "Secure usage rights up front and run winning videos from your own ad accounts through creator whitelisting. A single winning UGC ad should be recut into five lengths and aspect ratios before you commission the next one." },
      { h2: "Key takeaways" },
      { ul: ["Hook on a problem in 3 seconds", "Show the product solving it fast", "Keep it native, not polished", "Brief creators with a structure, not just a vibe"] },
    ],
  },
  {
    slug: "calculate-ltv-for-subscription-app",
    title: "How to Calculate LTV for a Subscription App (Without a Data Team)",
    excerpt: "You don’t need a data warehouse to estimate lifetime value. Here’s a back-of-the-envelope method that’s good enough to make decisions.",
    category: "Analytics",
    author: A.kenji,
    date: "2025-04-02",
    readMins: 10,
    keywords: ["LTV", "lifetime value", "subscription metrics", "churn rate", "app monetization"],
    body: [
      { p: "Lifetime value sounds like it requires sophisticated modeling. For decision-making, a simple estimate beats a perfect one you never finish." },
      { h2: "The simple formula" },
      { p: "LTV ≈ (average monthly revenue per user × gross margin) ÷ monthly churn rate. If users pay $10/mo at 80% margin and churn 5% monthly, LTV ≈ ($10 × 0.8) ÷ 0.05 = $160." },
      { fig: "cohort-curves", caption: "Churn isn’t constant: early months churn hardest, so cohort curves refine the estimate." },
      { h2: "Use it against CAC" },
      { p: "The number itself matters less than the LTV:CAC ratio and payback period. Aim for LTV comfortably above CAC, with payback you can finance." },
      { h2: "Where the simple model breaks" },
      { p: "The formula assumes constant churn, which overstates LTV when early churn is high. Correct it cheaply: compute churn from month three onward once the leaky first weeks pass, or model the first three months separately from the steady state." },
      { fig: "gauge", caption: "LTV’s job is to set your acquisition ceiling — spend to a fraction of it, not all of it." },
      { h2: "Make it a habit, not a project" },
      { p: "Recompute quarterly and after every pricing or onboarding change. The trend matters more than the level: rising LTV means you can outbid competitors for the same user — the quietest possible competitive advantage." },
      { h2: "Key takeaways" },
      { ul: ["A simple LTV estimate beats none", "Always use gross margin, not revenue", "Pair LTV with CAC and payback", "Recompute as churn improves"] },
    ],
  },
  {
    slug: "tiktok-ads-for-app-installs",
    title: "TikTok Ads for App Installs: What Actually Works",
    excerpt: "TikTok can drive cheap installs at scale — or burn budget on users who never come back. Here’s how to make it profitable.",
    category: "Paid Media",
    author: A.tomas,
    date: "2025-05-13",
    readMins: 11,
    keywords: ["TikTok ads", "app install campaigns", "mobile UA", "social ads", "creative-first marketing"],
    body: [
      { p: "TikTok is a creative platform first and an ad platform second. Win the feed with native content and the cost efficiency follows; lose it and no bid strategy will save you." },
      { h2: "Make ads that don’t look like ads" },
      { p: "Native, sound-on, creator-style content outperforms anything that screams ‘advertisement.’ Repurpose trends, but tie them to a real product moment." },
      { fig: "ugc-phone", caption: "Creator-style content wins the feed; polish reads as an ad and gets skipped." },
      { h2: "Optimize for retained users" },
      { p: "Cheap installs mean nothing if they churn. Optimize toward post-install events and watch day-7 retention, not just CPI." },
      { fig: "retention-curve", caption: "Judge TikTok on the retention curve of the users it brings — not the install price." },
      { h2: "Refresh faster than anywhere else" },
      { p: "Creative fatigues on TikTok in days, not weeks. Plan for a multiple of your Meta creative volume, recut winners into new hooks before performance decays, and let the comments section write your next three scripts." },
      { h2: "Use Spark Ads to borrow trust" },
      { p: "Boosting a creator’s post from their own handle keeps the social proof — comments, likes, follows — attached to the ad. Negotiate Spark access in every creator deal; the same video from a brand handle performs measurably worse." },
      { h2: "Key takeaways" },
      { ul: ["Creative is the whole game on TikTok", "Go native and sound-on", "Optimize to post-install events", "Judge it on retained users, not CPI"] },
    ],
  },
  {
    slug: "server-side-tracking-death-of-the-pixel",
    title: "Server-Side Tracking & the Death of the Pixel: A Practical Guide",
    excerpt: "Browser pixels are fading. Server-side tracking is how you keep your measurement and optimization alive.",
    category: "Analytics",
    author: A.kenji,
    date: "2025-03-19",
    readMins: 12,
    keywords: ["server-side tracking", "conversions API", "first-party data", "iOS privacy", "ad measurement"],
    body: [
      { p: "Between privacy changes and ad blockers, client-side pixels miss a growing share of conversions. Server-side tracking sends events from your own infrastructure, restoring signal." },
      { h2: "Why it matters now" },
      { p: "Lost events mean worse optimization and undercounted ROAS. The algorithms learn from the data you send — feed them clean, complete events and performance improves." },
      { fig: "inflated-bar", caption: "Missing events undercount conversions and mislead both you and the algorithm." },
      { h2: "How to implement it" },
      { p: "Adopt the platform Conversions APIs, deduplicate against any remaining pixel, and pass hashed first-party identifiers. Start with your most valuable events." },
      { h2: "What actually changes when you switch" },
      { p: "Teams typically see 15–30% more conversions reported once server events flow — not new revenue, just restored visibility. Expect platform optimization to improve over the following weeks as the algorithms retrain on complete data." },
      { fig: "dashboard", caption: "After migration, event match quality becomes a metric worth watching weekly." },
      { h2: "A pragmatic migration order" },
      { p: "Start with your highest-value event on your biggest channel, run pixel and server events in parallel with deduplication, verify match quality, then roll down the funnel and across channels. Never flip everything at once — you lose the ability to debug." },
      { h2: "Key takeaways" },
      { ul: ["Pixels miss more conversions every year", "Server-side restores optimization signal", "Deduplicate to avoid double-counting", "Prioritize your highest-value events"] },
    ],
  },
  {
    slug: "incrementality-testing-explained",
    title: "Incrementality Testing: Proving Your Ads Actually Drive Growth",
    excerpt: "Attribution tells you what got credit. Incrementality tells you what you actually caused. Here’s how to run a test.",
    category: "Analytics",
    author: A.kenji,
    date: "2025-06-03",
    readMins: 12,
    keywords: ["incrementality testing", "geo experiments", "holdout test", "causal measurement", "marketing ROI"],
    body: [
      { p: "The hardest question in marketing is also the most important: would this conversion have happened anyway? Incrementality testing answers it with experiments, not attribution windows." },
      { h2: "Geo and holdout tests" },
      { p: "Split markets or audiences into test and control, run your spend in one, and measure the lift. The difference is your incremental impact — the part you actually caused." },
      { fig: "mix-model", caption: "MMM and incrementality tests validate each other — models propose, experiments dispose." },
      { h2: "When to test" },
      { p: "Test before scaling a major channel and whenever a channel’s reported ROAS looks too good to be true. The cost of the test is trivial against the budget it informs." },
      { h2: "Design tests that can actually answer" },
      { p: "Pick markets that are similar and large enough to detect the effect you expect, run for at least two purchase cycles, and decide the success threshold before launch. An underpowered test is worse than no test — it hands you a confident wrong answer." },
      { fig: "gauge", caption: "Size the test budget to the decision it informs — a $5k test protecting a $500k budget is cheap." },
      { h2: "Turning lift into budget moves" },
      { p: "If a channel shows 20% incrementality against 100% claimed attribution, don’t just cut it — reprice it. Recompute its true CAC at the incremental rate, rebalance budget toward channels with the best incremental payback, and retest twice a year as auctions shift." },
      { h2: "Key takeaways" },
      { ul: ["Attribution ≠ causation", "Use geo or holdout experiments", "Measure lift, not last-click", "Test before you scale spend"] },
    ],
  },
  {
    slug: "90-day-growth-plan-for-startups",
    title: "The 90-Day Growth Plan Every Seed-Stage Startup Needs",
    excerpt: "No six-month strategy decks. Here’s the 90-day operating plan we use to take a startup from zero to a repeatable channel.",
    category: "Strategy",
    author: A.elena,
    date: "2025-02-11",
    readMins: 11,
    keywords: ["growth plan", "seed stage", "startup marketing", "go-to-market", "user acquisition"],
    body: [
      { p: "Early-stage growth fails from vagueness, not lack of effort. A tight 90-day plan with one north-star metric beats an ambitious roadmap nobody executes." },
      { h2: "Days 1–30: diagnose and instrument" },
      { p: "Fix tracking, define your activation event, and run small tests across two or three channels. The goal is clean data and early signal, not scale." },
      { fig: "dashboard", caption: "Week one: a shared dashboard, so every later decision argues with data instead of opinions." },
      { h2: "Days 31–60: double down" },
      { p: "Cut what isn’t working, concentrate budget and creative on the channel showing life, and build the first repeatable playbook." },
      { h2: "Days 61–90: systematize" },
      { p: "Turn the winning motion into a weekly cadence of experiments and creative, and set the efficiency targets you’ll scale against." },
      { fig: "steps-spark", caption: "Define activation precisely — the plan aims every experiment at that moment." },
      { h2: "The cadence is the plan" },
      { p: "A Monday metrics review, a Thursday experiment review, and a written log of every test — that rhythm is what separates a plan from a wish. Ninety days is thirteen shots at learning; don’t waste four of them deciding in Slack." },
      { h2: "What to deliberately ignore" },
      { p: "Brand campaigns, five-channel experiments, attribution perfectionism, and tooling migrations all belong after day 90. The plan works because of what it excludes." },
      { h2: "Key takeaways" },
      { ul: ["Pick one north-star metric", "Instrument before you scale", "Concentrate on the channel with signal", "Systematize the winner into a cadence"] },
    ],
  },
  {
    slug: "google-ads-for-mobile-apps",
    title: "Google Ads for Mobile Apps: Beyond Universal App Campaigns",
    excerpt: "App campaigns are mostly automated — but you still have powerful levers. Here’s how to get more from Google’s app inventory.",
    category: "Paid Media",
    author: A.tomas,
    date: "2025-04-16",
    readMins: 11,
    keywords: ["Google App Campaigns", "mobile app ads", "AC campaigns", "app marketing", "Google Ads"],
    body: [
      { p: "Google App Campaigns hand most controls to the algorithm, which makes the inputs you do control — assets and bidding goals — disproportionately important." },
      { h2: "Feed the asset machine" },
      { p: "App Campaigns assemble ads from your text, image, and video assets. The more high-quality, varied assets you provide, the more combinations Google can optimize." },
      { fig: "ad-grid", caption: "Asset variety is the lever: give the machine distinct angles, not five crops of one idea." },
      { h2: "Bid to the right event" },
      { p: "Choose install-volume, in-app action, or value bidding based on your maturity. As you gather data, move down the funnel toward value-based goals." },
      { h2: "Read the asset report like a creative brief" },
      { p: "Google grades assets Low, Good, and Best. Replace the Lows every two weeks, make more things like your Bests, and treat the report as your cheapest source of creative direction — it’s telling you exactly what the auction wants." },
      { fig: "gauge", caption: "Bidding goals should mature with your data: installs first, then actions, then value." },
      { h2: "Give the algorithm room and time" },
      { p: "App Campaigns need budget headroom above the bid target and a couple of weeks of patience after each change. Constant tinkering resets learning; schedule changes in batches and judge results over weeks, not days." },
      { h2: "Key takeaways" },
      { ul: ["Assets are your main lever", "Provide varied video and image", "Match bidding goal to data maturity", "Progress toward value-based bidding"] },
    ],
  },
  {
    slug: "app-store-listings-that-rank-and-convert",
    title: "How to Write App Store Listings That Rank and Convert",
    excerpt: "Your store listing is both an SEO asset and a sales page. Here’s how to write one that does both jobs.",
    category: "ASO",
    author: A.aisha,
    date: "2025-05-28",
    readMins: 10,
    keywords: ["app store listing", "ASO copywriting", "app description", "keyword optimization", "conversion rate"],
    body: [
      { p: "A great listing serves two masters: the algorithm that ranks you and the human deciding whether to install. Write for both, in that order of placement." },
      { h2: "Title and subtitle carry the keywords" },
      { p: "Your most valuable, highest-volume keywords belong in the title and subtitle. These fields weigh most heavily in ranking — don’t waste them on fluff." },
      { fig: "search-result", caption: "Rank for the query, then win the tap — the listing does both jobs." },
      { h2: "Lead the description with value" },
      { p: "Most users read only the first lines. Open with the core benefit and social proof, then expand into features for those who scroll." },
      { h2: "Screenshots are ads — treat them like it" },
      { p: "Most visitors decide from the first two screenshots without ever scrolling. Lead with your strongest outcome, add short benefit captions, and test screenshot order the way you test ad creative — the conversion lift compounds across every channel that lands on your listing." },
      { fig: "ad-grid", caption: "Store screenshot tests: same discipline as ad testing, often bigger lift." },
      { h2: "Localize like you mean it" },
      { p: "Translated keywords are table stakes; localized screenshots and culturally adapted messaging are where conversion moves. Prioritize your top five store countries by revenue and localize them fully rather than shallowly translating twenty." },
      { h2: "Key takeaways" },
      { ul: ["Put top keywords in title/subtitle", "Lead with benefit and proof", "Write for ranking and conversion", "Refresh as keyword trends shift"] },
    ],
  },
  {
    slug: "onboarding-optimization-activate-users",
    title: "Onboarding Optimization: Turn Signups Into Activated Users",
    excerpt: "Most churn happens in the first session. Here’s how to design onboarding that gets users to value fast.",
    category: "Retention",
    author: A.aisha,
    date: "2025-03-31",
    readMins: 11,
    keywords: ["onboarding", "activation", "user retention", "product adoption", "first session"],
    body: [
      { p: "You can buy installs, but you can’t buy activation. The first session is where most users decide whether to stay — and where most acquisition budget quietly dies." },
      { h2: "Define your activation moment" },
      { p: "Pin down the specific action that predicts retention — the ‘aha’ that turns a curious signup into a user. Everything in onboarding should drive toward it." },
      { fig: "funnel", caption: "Map every step between signup and first value — each one leaks users." },
      { h2: "Remove every non-essential step" },
      { p: "Each screen between signup and value is a place to lose people. Defer permissions, settings, and account details until after the first win." },
      { h2: "Instrument each step, fix the biggest leak" },
      { p: "Track completion of every onboarding screen and sort by drop-off. Fix the single biggest leak, remeasure, repeat. Onboarding optimization is boring in exactly the way profitable things are boring." },
      { fig: "retention-curve", caption: "Activated users bend the retention curve — the payoff shows up in every cohort after." },
      { h2: "Personalize the first run" },
      { p: "One question — ‘what are you here to do?’ — lets you route users to the shortest path for their goal. A generic tour serves nobody; a routed first run gets each segment to its own aha faster." },
      { h2: "Key takeaways" },
      { ul: ["Activation can’t be purchased — only designed", "Define the moment that predicts retention", "Cut steps before first value", "Defer friction until after the aha"] },
    ],
  },
  {
    slug: "marketing-mix-modeling-for-startups",
    title: "Marketing Mix Modeling for Startups: A Lightweight Approach",
    excerpt: "MMM used to require a consultancy and a year. Here’s a lightweight version startups can actually use to allocate budget.",
    category: "Analytics",
    author: A.kenji,
    date: "2025-06-17",
    readMins: 12,
    keywords: ["marketing mix modeling", "MMM", "budget allocation", "media measurement", "privacy-safe attribution"],
    body: [
      { p: "As tracking erodes, marketing mix modeling is making a comeback — but you don’t need an enterprise budget. A lightweight model can guide allocation without per-user tracking." },
      { h2: "What MMM actually does" },
      { p: "MMM uses aggregate spend and outcome data over time to estimate each channel’s contribution. It’s privacy-safe because it never needs individual user data." },
      { fig: "dashboard", caption: "Weekly spend and outcomes by channel: the only data a lightweight MMM needs." },
      { h2: "Start simple" },
      { p: "Begin with a transparent regression on weekly spend and conversions, validate against geo tests, and refine. Directionally right beats precisely wrong." },
      { h2: "The data checklist" },
      { p: "Two years of weekly data is ideal, one is workable: spend by channel, conversions or revenue, plus known events — launches, price changes, seasonality. Clean data beats clever modeling; most MMM failures are data failures." },
      { fig: "channels", caption: "The model’s job is allocation: shift budget toward channels with the best marginal return." },
      { h2: "From coefficients to decisions" },
      { p: "Use the model to answer one question per quarter: where does the next dollar go? Shift 10–15% of budget toward the channels the model favors, watch blended results, and feed the outcome back in. Small validated moves beat grand reallocation." },
      { h2: "Key takeaways" },
      { ul: ["MMM is privacy-safe by design", "It guides allocation, not per-user targeting", "Start with a simple model", "Validate with incrementality tests"] },
    ],
  },
  {
    slug: "how-much-to-spend-on-user-acquisition",
    title: "How Much Should You Spend on User Acquisition?",
    excerpt: "There’s no magic percentage. Here’s a principled way to set your acquisition budget based on payback and growth goals.",
    category: "Strategy",
    author: A.elena,
    date: "2025-04-29",
    readMins: 10,
    keywords: ["marketing budget", "user acquisition spend", "CAC", "payback period", "growth budgeting"],
    body: [
      { p: "‘What percentage of revenue should we spend on marketing?’ is the wrong question. The right one is: how much can we spend while keeping payback inside our tolerance?" },
      { h2: "Let payback set the ceiling" },
      { p: "If your unit economics support a 9-month payback and you can finance it, you can spend as long as the marginal payback holds. Efficiency, not a fixed percentage, sets the cap." },
      { fig: "payback-clock", caption: "Your tolerance for payback — six, nine, twelve months — is the real budget ceiling." },
      { h2: "Watch the marginal cost" },
      { p: "Costs rise as you scale. Track the payback of your last dollar, not your average — that’s where the real ceiling lives." },
      { fig: "scale-steps", caption: "Marginal payback holding steady is the green light to keep pressing spend." },
      { h2: "A worked example" },
      { p: "Suppose your payback tolerance is nine months and your current marginal payback is five. That gap is your growth budget: raise spend in 20% steps until marginal payback approaches nine, then hold. The answer to ‘how much’ is a process, not a percentage." },
      { h2: "When to pull back" },
      { p: "Cut when marginal payback breaches tolerance for a sustained period, not on one bad week. Pull from the worst marginal segments first — pausing your best campaigns to hit a blended number is how teams shrink their way into trouble." },
      { h2: "Key takeaways" },
      { ul: ["Budget by payback, not percentage", "Spend while marginal payback holds", "Watch marginal, not average, cost", "Finance growth you can actually afford"] },
    ],
  },
  {
    slug: "creative-testing-framework",
    title: "The Creative Testing Framework We Use to Beat Control",
    excerpt: "Random creative tests waste budget. This is the structured framework we use to reliably find new winners.",
    category: "Creative",
    author: A.aisha,
    date: "2025-05-19",
    readMins: 11,
    keywords: ["creative testing", "ad testing framework", "A/B testing ads", "performance creative", "iteration"],
    body: [
      { p: "Testing ‘a bunch of creative and seeing what sticks’ is how budgets evaporate. A framework turns testing into a compounding learning system." },
      { h2: "Test at the concept level" },
      { p: "Group ads by the idea they test — a hook, an angle, a format — so a result teaches you something reusable, not just which thumbnail won." },
      { fig: "ad-grid", caption: "Group ads by the idea they test, so results teach principles — not thumbnails." },
      { h2: "Give tests room to breathe" },
      { p: "Underfunded tests produce noise. Allocate enough budget per concept to reach a confident read, then scale winners with variations." },
      { h2: "A calendar that compounds" },
      { p: "We run two testing sprints a week: new concepts on Tuesdays, iterations on winners on Fridays. Every result lands in a shared log with the hypothesis, spend, and verdict. Six months of that log is worth more than any agency’s ‘best practices’ deck." },
      { fig: "dashboard", caption: "Judge tests on cost per qualified outcome — CTR is a clue, not a verdict." },
      { h2: "Read past the click" },
      { p: "A high-CTR ad that attracts the wrong users is a beautiful trap. Score every test on downstream quality — activation, trial-to-paid, early retention — before scaling it." },
      { h2: "Key takeaways" },
      { ul: ["Test concepts, not random ads", "Fund tests to significance", "Scale winners with variations", "Turn results into reusable principles"] },
    ],
  },
  {
    slug: "seo-for-saas-programmatic-strategy",
    title: "SEO for SaaS: A Programmatic Strategy That Scales",
    excerpt: "Blog posts alone won’t scale SaaS SEO. Here’s how programmatic and product-led SEO build a durable organic moat.",
    category: "SEO",
    author: A.elena,
    date: "2025-03-08",
    readMins: 13,
    keywords: ["SaaS SEO", "programmatic SEO", "content strategy", "organic growth", "search marketing"],
    body: [
      { p: "Most SaaS SEO stalls because it relies on hand-written posts chasing competitive head terms. The teams that win build systems that scale across thousands of long-tail intents." },
      { h2: "Programmatic pages at scale" },
      { p: "Templates powered by structured data can target large families of related queries — integrations, comparisons, use cases — that individually have low volume but collectively dominate." },
      { fig: "search-result", caption: "Long-tail intents — comparisons, integrations, use cases — are where programmatic pages win." },
      { h2: "Product-led content" },
      { p: "Free tools, templates, and calculators earn links and rank for high-intent terms while showcasing your product. They’re assets, not just articles." },
      { h2: "Own the comparison surface" },
      { p: "Buyers search ‘you vs competitor’ late in their decision. Build honest comparison pages for every rival before an affiliate site does it for you — high intent, low volume, absurdly high conversion." },
      { fig: "loop-funnel", caption: "Organic compounds: every ranking asset keeps feeding the funnel without new spend." },
      { h2: "Measure SEO like a channel" },
      { p: "Track signups and revenue from organic landing pages, not just rankings and traffic. When SEO reports CAC alongside paid channels, budget conversations change — organic usually wins them." },
      { h2: "Key takeaways" },
      { ul: ["Hand-written posts don’t scale alone", "Use programmatic pages for long-tail", "Build product-led tools that rank", "Compound authority over quarters"] },
    ],
  },
  {
    slug: "push-notifications-that-dont-get-uninstalled",
    title: "Push Notifications That Don’t Get Users to Uninstall",
    excerpt: "Push can drive retention or drive uninstalls. Here’s how to use it without burning your audience.",
    category: "Retention",
    author: A.aisha,
    date: "2025-06-09",
    readMins: 10,
    keywords: ["push notifications", "mobile retention", "engagement", "lifecycle messaging", "opt-in rate"],
    body: [
      { p: "Push is the most direct line to your users — and the fastest way to lose them. The difference is relevance and restraint." },
      { h2: "Earn the opt-in" },
      { p: "Don’t ask for notification permission on first launch. Ask after the user has felt value and frame the benefit of opting in." },
      { fig: "steps-spark", caption: "Ask for permission after the first win — opt-in rates double when value comes first." },
      { h2: "Segment and trigger" },
      { p: "Behavior-triggered, segmented pushes outperform blasts every time. Send fewer, more relevant messages tied to what the user actually did." },
      { fig: "retention-curve", caption: "Relevant push lifts the curve; blasts flatten it right into the uninstall screen." },
      { h2: "Respect the clock" },
      { p: "Send in the user’s local daytime, cap total frequency across all campaigns, and honor quiet hours by default. The uninstall from a 3 a.m. notification costs more than the campaign earned." },
      { h2: "Deep link or don’t bother" },
      { p: "Every push should land the user exactly where the action happens — not on the home screen. Broken or lazy links teach users your notifications waste their time, and that lesson is permanent." },
      { h2: "Key takeaways" },
      { ul: ["Ask for opt-in after first value", "Segment by behavior", "Trigger on actions, don’t blast", "Fewer, more relevant pushes win"] },
    ],
  },
  {
    slug: "from-cpi-to-roas-aligning-acquisition-with-revenue",
    title: "From CPI to ROAS: Aligning Acquisition With Revenue",
    excerpt: "Optimizing to install cost can quietly destroy unit economics. Here’s how to move your optimization down the funnel to revenue.",
    category: "Strategy",
    author: A.tomas,
    date: "2025-04-04",
    readMins: 11,
    keywords: ["CPI", "ROAS", "value optimization", "revenue marketing", "funnel optimization"],
    body: [
      { p: "Cheap installs feel like progress, but a low CPI with poor retention is a fast way to lose money at scale. The fix is to optimize toward revenue events, not the install." },
      { h2: "Move the optimization event down" },
      { p: "As you gather post-install data, shift platform optimization from installs to trials, purchases, or predicted value. You’ll pay more per install and make more per user." },
      { fig: "funnel", caption: "Optimize deeper in the funnel as data allows: install → trial → purchase → value." },
      { h2: "Feed value signals back" },
      { p: "Send revenue and quality events back to the platforms so their models learn to find users who pay, not just users who tap." },
      { fig: "server-relay", caption: "Revenue events flowing back teach the platforms which users are worth finding." },
      { h2: "The transition plan" },
      { p: "Move one campaign at a time, expect CPI to rise 20–40% while cost per paying user falls, and give each step two weeks before judging. Teams that flip everything at once panic at the CPI spike and retreat right before the economics improve." },
      { h2: "Reset the scoreboard" },
      { p: "Change what the team reports before you change what the platform optimizes. When the weekly review leads with cost per trial and payback — not CPI — the whole organization starts making better trade-offs automatically." },
      { h2: "Key takeaways" },
      { ul: ["Low CPI can hide bad economics", "Optimize to revenue events", "Pay more per install, earn more per user", "Feed value signals to the algorithm"] },
    ],
  },
  {
    slug: "scaling-paid-spend-without-tanking-efficiency",
    title: "Scaling Paid Spend Without Tanking Efficiency",
    excerpt: "Doubling budget rarely doubles results. Here’s how to scale spend while protecting your payback period.",
    category: "Paid Media",
    author: A.tomas,
    date: "2025-05-26",
    readMins: 12,
    keywords: ["scaling ads", "paid media", "efficiency", "budget scaling", "diminishing returns"],
    body: [
      { p: "Scaling is where good economics go to die. As spend rises, you reach less efficient audiences and costs climb — unless you expand the frontier deliberately." },
      { h2: "Expand inputs, not just budget" },
      { p: "More budget on the same audiences hits diminishing returns fast. Scale by adding creative, geos, and channels — new inputs, not just a bigger number." },
      { fig: "channels", caption: "Scale is horizontal: new creative, geos, and channels expand the efficient frontier." },
      { h2: "Watch marginal efficiency" },
      { p: "Track the payback of incremental spend, not the blended average. When the marginal dollar exceeds your tolerance, you’ve found the ceiling for now." },
      { h2: "Raise budgets like you mean to keep them" },
      { p: "Increase in steps of about 20% every few days rather than doubling overnight — auction systems re-learn on large jumps and efficiency craters. Scale into strength: put increases behind your proven audiences and creative, not your experiments." },
      { fig: "ad-grid", caption: "Creative volume must scale with budget — fatigue arrives faster at higher spend." },
      { h2: "Pre-build the next frontier" },
      { p: "The time to test your next geo, channel, and creative direction is while the current ones still work. Scaling teams hit ceilings; compounding teams always have the next expansion half-proven before they need it." },
      { h2: "Key takeaways" },
      { ul: ["Budget alone hits diminishing returns", "Scale with new creative, geos, channels", "Track marginal efficiency", "Respect the ceiling until you can lift it"] },
    ],
  },
  {
    slug: "metrics-dashboard-every-growth-team-should-build",
    title: "The Metrics Dashboard Every Growth Team Should Build",
    excerpt: "If your whole team can’t see the same numbers, you’ll argue instead of decide. Here’s the dashboard we set up first.",
    category: "Analytics",
    author: A.kenji,
    date: "2025-02-28",
    readMins: 10,
    keywords: ["growth dashboard", "marketing metrics", "KPIs", "reporting", "data visibility"],
    body: [
      { p: "Growth teams move fast when everyone trusts the same numbers. A shared, simple dashboard ends the weekly debate about whose figures are right." },
      { h2: "The metrics that belong on it" },
      { p: "Spend, blended CAC, payback period, new users, activation rate, and retention by cohort. Resist the urge to add fifty vanity metrics." },
      { fig: "payback-clock", caption: "Payback belongs on the front page — it’s the number that decides how hard you can push." },
      { h2: "Make it live and shared" },
      { p: "A dashboard nobody opens is worthless. Connect it to source data, keep it current, and put it where the whole team works." },
      { fig: "cohort-curves", caption: "A cohort view answers the only question that matters: is it getting better?" },
      { h2: "Write the definitions down" },
      { p: "Half of all metric arguments are definition arguments in disguise. Document exactly how CAC, activation, and retention are computed — including what’s excluded — and link the definitions from the dashboard itself." },
      { h2: "Give it a ritual" },
      { p: "A dashboard nobody discusses is decoration. Open Monday’s growth meeting with it, assign an owner to every anomaly, and close the loop the following week. The ritual, not the tool, is what changes decisions." },
      { h2: "Key takeaways" },
      { ul: ["Shared numbers end arguments", "Track spend, CAC, payback, activation, retention", "Keep it simple and live", "Put it where the team already works"] },
    ],
  },
  {
    slug: "cohort-analysis-101-for-app-marketers",
    title: "Cohort Analysis 101 for App Marketers",
    excerpt: "Averages hide the truth; cohorts reveal it. Here’s how to read cohort curves and act on them.",
    category: "Analytics",
    author: A.kenji,
    date: "2025-06-20",
    readMins: 11,
    keywords: ["cohort analysis", "retention curves", "app analytics", "user behavior", "retention rate"],
    body: [
      { p: "Blended metrics average away the signal you need. Cohort analysis groups users by when they joined, so you can see whether your product and acquisition are actually improving." },
      { h2: "Read the curve, not the point" },
      { p: "A retention curve that flattens means you have a core of sticky users — a real foundation. A curve that decays to zero means you’re renting users, not keeping them." },
      { fig: "retention-curve", caption: "The flattening point is your product’s verdict: a floor means you’re keeping users." },
      { h2: "Compare cohorts over time" },
      { p: "If newer cohorts retain better than older ones, your product and onboarding are improving. That trend is the clearest sign growth is healthy." },
      { fig: "ab-split", caption: "Cut cohorts by channel and campaign — averages across sources hide who’s really retaining." },
      { h2: "Slice by source before you celebrate" },
      { p: "A strong blended cohort can hide one channel’s excellent retention subsidizing another’s churn. Cohort every channel separately; the spread between best and worst source is usually the biggest budget insight you’ll find all quarter." },
      { h2: "From reading curves to moving them" },
      { p: "Cohorts diagnose, actions cure: onboarding fixes lift the curve’s start, lifecycle messaging lifts its middle, and pricing or habit features raise the floor. Re-cohort after every major change — the before/after pair is the cleanest experiment you’ll ever run for free." },
      { h2: "Key takeaways" },
      { ul: ["Averages hide retention reality", "Look for the curve to flatten", "Compare cohorts to spot improvement", "Healthy cohorts justify more spend"] },
    ],
  },
  {
    slug: "how-to-diversify-beyond-meta-and-google",
    title: "How to Diversify Beyond Meta and Google",
    excerpt: "Two-channel dependence is a risk, not a strategy. Here’s how to test and add new channels without wasting budget.",
    category: "Paid Media",
    author: A.tomas,
    date: "2025-03-22",
    readMins: 11,
    keywords: ["channel diversification", "paid channels", "TikTok", "Reddit ads", "media mix"],
    body: [
      { p: "When two platforms own your growth, a single algorithm change or price hike can wipe out your margins overnight. Diversification is insurance — and often new efficiency." },
      { h2: "Test with a real budget and real creative" },
      { p: "New channels fail when teams give them scraps. Commit a genuine test budget and native creative for each platform — a half-hearted test teaches nothing." },
      { fig: "ugc-phone", caption: "Each platform has a native language — TikTok wants creator video, not resized banner ads." },
      { h2: "Match the channel to the motion" },
      { p: "TikTok rewards native video; Reddit rewards community fit; search rewards intent. Bring the right creative and offer to each, not a recycled Meta ad." },
      { fig: "gauge", caption: "Give a new channel a defined test budget and a decision date — then honor both." },
      { h2: "A graduation framework" },
      { p: "Stage one: a small budget to test creative fit and early CPA. Stage two: matched spend to verify quality — activation and retention, not just installs. Stage three: scale toward marginal-payback parity with your core channels. Kill or graduate at each gate; zombie channels eat focus." },
      { h2: "Diversification is a portfolio decision" },
      { p: "The goal isn’t five mediocre channels — it’s two or three strong ones plus a rotating test slot. Concentration with a pipeline of options beats both monogamy and sprawl." },
      { h2: "Key takeaways" },
      { ul: ["Two-channel reliance is fragile", "Fund new-channel tests properly", "Use native creative per platform", "Diversify before you’re forced to"] },
    ],
  },
  {
    slug: "profitable-acquisition-engine-before-series-b",
    title: "Building a Profitable Acquisition Engine Before Series B",
    excerpt: "Investors fund defensible growth, not just growth. Here’s how to show efficient, repeatable acquisition before you raise.",
    category: "Strategy",
    author: A.elena,
    date: "2025-06-27",
    readMins: 12,
    keywords: ["Series B", "fundraising", "unit economics", "scalable growth", "acquisition engine"],
    body: [
      { p: "By Series B, investors want proof that growth funds itself. A profitable, repeatable acquisition engine is worth more than a spike in vanity metrics." },
      { h2: "Show clean unit economics" },
      { p: "Defensible CAC, healthy payback, and improving cohort retention tell investors your growth is real. Tie every acquisition dollar to revenue you can trust." },
      { fig: "cohort-curves", caption: "Improving cohorts are the slide investors remember — efficiency that trends better over time." },
      { h2: "Prove it’s repeatable" },
      { p: "One lucky channel isn’t an engine. Show diversified channels, a creative system, and attribution you’d stake the round on." },
      { fig: "dashboard", caption: "Investor-grade reporting: one source of truth for CAC, payback, and retention." },
      { h2: "The diligence packet, before diligence" },
      { p: "Prepare CAC by channel by quarter, cohort retention triangles, payback trends, and channel concentration before anyone asks. Clean numbers signal an operator; scrambling for them signals luck." },
      { h2: "Narrate the engine, not the spikes" },
      { p: "The story that raises isn’t ‘we grew 40% last quarter’ — it’s ‘every dollar in produces a predictable return, and here are eight quarters of proof.’ Growth spikes raise questions; engines raise rounds." },
      { h2: "Key takeaways" },
      { ul: ["Investors fund defensible growth", "Show clean CAC and payback", "Prove repeatability across channels", "Make attribution investor-grade"] },
    ],
  },
];

export function getAllSlugs() {
  return posts.map((p) => p.slug);
}

export function getPost(slug) {
  return posts.find((p) => p.slug === slug);
}

export function getRelatedPosts(slug, n = 3) {
  const current = getPost(slug);
  if (!current) return [];
  const sameCat = posts.filter((p) => p.slug !== slug && p.category === current.category);
  const others = posts.filter((p) => p.slug !== slug && p.category !== current.category);
  return [...sameCat, ...others].slice(0, n);
}

export function formatDate(iso) {
  return new Date(iso).toLocaleDateString("en-US", {
    year: "numeric",
    month: "short",
    day: "numeric",
  });
}
